### PR TITLE
Chat channel implementation

### PR DESCRIPTION
**Pull request by rossengeorgiev**
This PR should be used to discuss the development of this feature. Continuation of #20 

Further changes via PR should point at `chat_channel` branch

### CODE REVIEW

**Comment by Philaeux** [comment]
The first commit is mainly low level features, close to what is already done in node-dota2. We can build high level features with what you suggested in the other pull request: store channel information, store members... 

I will think about what would be good high level endpoints.

**Comment by rossengeorgiev** [comment]
Derp, I've lose some code I wrote for this in recent HDD failure. Will try to bring a rewrite soon™

**Comment by rossengeorgiev** [comment]
.... well nice job github....

**Comment by rossengeorgiev** [comment]
This is screwed

**Pull request closed without merging**
